# Generated by Django 4.2.2 on 2023-06-25 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа')),
                ('serial_number_mask', models.CharField(max_length=50, verbose_name='Маска серийного номера')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='equ_typ__name__idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Удалено')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_by', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='backend.equipmenttype', verbose_name='Тип оборудования')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['is_archived', 'equipment_type', 'serial_number'],
                'indexes': [models.Index(fields=['is_archived', 'equipment_type', 'serial_number'], name='equ__type_serial_number__idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('equipment_type', 'serial_number'), name='equ__type_serial_number__unq'),
        ),
    ]
