# Generated by Django 4.2.2 on 2023-06-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_equipment_options_alter_equipmenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Serial number of equipment'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='serial_number_mask',
            field=models.CharField(max_length=50, verbose_name='Mask of serial numbers'),
        ),
        migrations.AddConstraint(
            model_name='equipmenttype',
            constraint=models.UniqueConstraint(fields=('name',), name='equ_typ__name__unq'),
        ),
    ]
